
#' Blended survival object
#'
#' This is the main function in the \pkg{blendR} package.
#' Two survival curves are supplied and blended according to
#' the blending distribution characterised by the blending interval and
#' the beta distribution parameters.
#'
#' @details
#' The `obs_Surv` and `ext_Surv` arguments accept several types of fitted
#' survival models and data structures. Exhaustively, the accepted objects are:
#'   - `survHE` objects: Fitted survival models generated by the `fit.models()` function from the \pkg{survHE} package.
#'   - `inla` objects: Bayesian survival models fitted using the \pkg{INLA} package, typically generated via `INLA::inla()` or the helper function `fit_inla_pw()`.
#'   - `flexsurvreg` objects: Parametric survival models generated by `flexsurvreg()` or `flexsurvspline()` from the \pkg{flexsurv} package.
#'   - `matrix` objects: A numeric matrix of pre-calculated survival probabilities, where rows correspond to discrete time points and columns correspond to simulations.
#'   - `numeric` vectors: A single numeric vector of pre-calculated survival probabilities (e.g., extracted from a Kaplan-Meier estimate like `survival::survfit()$surv}`.
#'
#' These objects are processed internally using the `make_surv()` S3 generic to ensure they are converted into a standardized format.
#'
#' @param obs_Surv,ext_Surv Observed and external data survival curves.
#'    These can come from \pkg{survHE}, \pkg{INLA} or \pkg{flexsurv} fits.
#' @param blend_interv A named list containing `min` and `max` values
#'    defining the blending interval (e.g., `list(min = 48, max = 150)`).
#' @param beta_params A named list containing the shape parameters `alpha`
#'    and `beta` of a beta distribution (e.g., `list(alpha = 3, beta = 3)`).
#' @param times A vector of times for which the survival curves
#'              are to be computed; optional.
#' @param nsim The number of simulations from the distribution of
#'             the survival curves; default 100.
#'
#' @return An object of class `blended`, which is a list containing the following elements:
#'
#' - `S`: A data frame with the point estimates of the blended survival curve. If `nsim > 1`, it also includes the lower (`low`) and upper (`upp`) 95\% credible intervals.
#' - `sim`: Currently `NA`.
#' - `nsim`: The number of simulations used.
#' - `mat`: A matrix of the simulated blended survival probabilities (rows represent time points, columns represent simulations).
#' - `des.mat`: Currently `NA`.
#' - `times`: A numeric vector of the time points at which the survival curves were evaluated.
#' - `S_ext`: A matrix of the simulated external survival probabilities.
#' - `S_obs`: A matrix of the simulated observed survival probabilities.
#' - `weight`: A numeric vector of the weights applied at each time point, derived from the beta distribution.
#' - `blend_interv`: The blending interval used.
#' - `beta_params`: The parameters of the beta distribution used for blending.
#'
#' @seealso
#' [survHE::fit.models()], [INLA::inla()], [flexsurv::flexsurvreg()],
#' [flexsurv::flexsurvspline()], [make_surv()]
#'
#' @references
#' Che, Z., Green, N., & Baio, G. (2022). Blended Survival Curves: A New Approach
#' to Extrapolation for Time-to-Event Outcomes from Clinical Trials in Health
#' Technology Assessment. Medical Decision Making, 43(3), 299-310.
#' <doi:10.1177/0272989X221134545>.
#'
#' @importFrom stats pbeta
#' @export
#'
#' @examplesIf rlang::is_installed("survHEhmc")
#'
#' library(survHE)
#'
#' ## trial data
#' data("TA174_FCR", package = "blendR")
#'
#' ## externally estimated data
#' data_sim <- ext_surv_sim(t_info = 144,
#'                          S_info = 0.05,
#'                          T_max = 180)
#' # observed survival times
#' obs_Surv <- fit.models(formula = Surv(death_t, death) ~ 1,
#'                        data = dat_FCR,
#'                        distr = "exponential",
#'                        method = "hmc")
#'
#' # external survival times
#' ext_Surv <- fit.models(formula = Surv(time, event) ~ 1,
#'                        data = data_sim,
#'                        distr = "exponential",
#'                        method = "hmc")
#'
#' # blending parameter values
#' blend_interv <- list(min = 48, max = 150)
#' beta_params <- list(alpha = 3, beta = 3)
#'
#' ble_Surv <- blendsurv(obs_Surv, ext_Surv, blend_interv, beta_params)
#'
#' # all survival curves
#' plot(ble_Surv)
#'
blendsurv <- function(obs_Surv, ext_Surv,
                      blend_interv,
                      beta_params = list(alpha = 3, beta = 3),
                      times = NULL,
                      nsim = 100) {

  # best guess at survival times
  if (is.null(times)) {
    S_times <- c(data_times(obs_Surv), data_times(ext_Surv))
    times <- pretty(S_times, n = 100)
  }

  tmax <- length(times)

  # external survival curve
  S_ext <- make_surv(ext_Surv, t = times, nsim = nsim)

  # observed data survival curve
  S_obs <- make_surv(obs_Surv, t = times, nsim = nsim)

  # parameters for the weight function
  wt_par <- list(a = blend_interv$min,
                 b = blend_interv$max,
                 shape1 = beta_params$alpha,
                 shape2 = beta_params$beta)

  w <- with(wt_par,
            stats::pbeta((times - a)/(b - a), shape1, shape2))

  # blended estimate
  mat <- matrix(NA, nrow = tmax, ncol = nsim)

  for (i in seq_len(nsim)) {
    mat[, i] <- S_obs[, i]^(1 - w) * S_ext[, i]^w
  }

  ## based on survHE::make.surv()
  if (nsim == 1) {
    # If nsim=1 then only save the point estimates of the survival curve
    S <- data.frame(S = rowMeans(mat))
  } else {
    # If nsim > 1 then also give the lower and upper quartile of the
    # underlying distribution
    S <- data.frame(S = rowMeans(mat),
                    low = apply(mat, 1, quantile, 0.025),
                    upp = apply(mat, 1, quantile, 0.975))
  }

  res <-
    list(S = S,
         sim = NA,
         nsim = nsim,
         mat = mat,
         des.mat = NA,
         times = times,
         S_ext = S_ext,     ##TODO: mat_ext etc?
         S_obs = S_obs,
         weight = w,
         blend_interv = blend_interv,
         beta_params = beta_params)

  structure(res, class = c("blended", class(res)))
}

